### ISSUE TITLE
Extension interferes with go.mod files

### ISSUE THREAD

**Issue by rome-user** [sweetppro/zed-xml#12]
The following line in `path_suffixes` seems to break detection of Go Mod files

https://github.com/sweetppro/zed-xml/blob/3a9d7afd176990ac82073ca3adbfc34b96a9e2e9/languages/xml/config.toml#L19

After installing this extension `go.mod` files are incorrectly marked as XML. Would it be possible to add some heuristic before activating XML mode? e.g. checking for the processing instruction `<?xml ... ?>` at the start of the file

**Comment by sweetppro** [comment]
This will be resolved in the next release which removes the hardcoded file extension associations, and instead uses the first_line_pattern regex

**Comment by sweetppro** [comment]
v0.0.7 is available now
