### ISSUE TITLE
Prettifier support?

### ISSUE THREAD

**Issue by ProjectInfinity** [sweetppro/zed-xml#13]
Hi, I am unsure if this belongs here but I couldn't find an answer and Discord was suggesting the extension maybe should support it..

I have XML and when I choose the action editor: format, I thought maybe it would format the XML to be more human readable but it did nothing. Is this something you can assist with?

**Comment by sweetppro** [comment]
Im not exactly sure why this isn't working. It should already support this. Im looking into this now to see if theres something which can be done

**Comment by sweetppro** [comment]
@ProjectInfinity Ive added a bug report on the main Zed repo:
https://github.com/zed-industries/zed/issues/19024

perhaps ad a thumbs up there to get some visibility from the Zed devs

**Comment by sweetppro** [comment]
this has been fixed in https://github.com/zed-industries/zed/pull/20758
