### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by reslear** [sweetppro/zed-xml#14]
from https://github.com/microsoft/vscode/blob/45a9f8902795ca9a10f411db90f690f67843d88d/extensions/xml/package.json#L58

**Comment by sweetppro** [comment]
@reslear v0.0.7 already support valid svg files

**Comment by jaydenseric** [comment]
@sweetppro this extension doesn't appear associate the file extension `.svg` to the XML language.

**Comment by sweetppro** [comment]
@jaydenseric valid svg documents will be recognised:
https://www.w3.org/TR/SVG2/struct.html#NewDocument

for non standard svg files, you can add a **file_types** override in your settings:
https://zed.dev/docs/configuring-zed#file-types

**Comment by jaydenseric** [comment]
Firstly, when you create a new `.svg` file in the editor, you want it to be in XML language for syntax highlighting before you start adding `<?xml version="1.0" standalone="no"?>` to the empty document. With how you have this extension currently, Zed will not start syntax highlighting after you type `<?xml ` at the start of the document. This issue alone is reason to add back all the XML file `path_suffixes`, not just for `.svg`.

Secondly, most SVG files served on the internet don't have `<?xml version="1.0" standalone="no"?>` at the start and SVG minifying software removes it. For example, here is the `.svg` file for the Apple logo served at apple.com:

https://www.apple.com/ac/globalfooter/8/en_US/assets/ac-footer/breadcrumbs/apple/icon_large.svg

<img width="1164" height="552" alt="Image" src="https://github.com/user-attachments/assets/415518ee-33b0-4d1f-aece-67aad99a227d" />

I'm skeptical that the `<?xml` is required by spec; if the server response for the `.svg` file includes the header `Content-Type: image/svg+xml; charset=UTF-8` then browsers know exactly what the contents of the file are. Grok AI says "The SVG 1.1 and SVG 2 specifications do not mandate the XML declaration.". Reading what you linked to in the spec, it doesn't seem to say a leading `<?xml` is required.

> for non standard svg files, you can add a file_types override in your settings

A know that already, but we install extensions for different languages to not have to customise our editor settings per every file type in our projects. I have setup project `.zed/settings.json` containing config so collaborators can clone the repo, and start coding and not have to configure their editor settings to get syntax highlighting when editing any of the files in the project:

```json
{
  "auto_install_extensions": {
    "deno": true,
    "dockerfile": true,
    "git-firefly": true,
    "graphql": true,
    "ini": true,
    "toml": true,
    "xml": true
  },
```
