### ISSUE TITLE
Tip if you want to install recommended extension

### ISSUE THREAD

**Issue by Angelk90** [sweetppro/zed-xml#3]
Hi! @sweetppro , When I open an xml file, it doesn't tell me something like this:

<img width="462" alt="Screenshot 2024-05-23 alle 00 25 21" src="https://github.com/sweetppro/zed-xml/assets/20476002/adca3783-0aaa-46c3-bed2-4939c91984ef">

It would be possible so that I also recognize `.entitlements` and `.plist` files that uses xml syntax.

Link entitlements: https://github.com/zed-industries/extensions/issues/777
Link plist: https://github.com/zed-industries/extensions/issues/771

**Comment by sweetppro** [comment]
> Hi! @sweetppro , When I open an xml file, it doesn't tell me something like this:
@Angelk90 strange... this may be an issue with Zed

> It would be possible so that I also recognize `.entitlements` and `.plist` files that uses xml syntax.
you should be able to add this to your settings.json:

```
"file_types": {
    "XML": ["entitlements", "plist"]
  },
```

**Comment by sweetppro** [comment]
added here https://github.com/sweetppro/zed-xml/pull/5
